### ISSUE TITLE
GitHub Authentication Plugin (github-oauth) breaks the reconcile loop

### ISSUE THREAD

**Issue by kboom** [jenkinsci/kubernetes-operator#278]
It appears that the activation of the Github Authentication Plugin breaks the reconcile loop.
Once it's broken the automatic reconfiguration doesn't happen and the rest of the user scripts are not executed.

How to retain the correct behaviour when the Github Plugin is used, which seems to be a reasonable requirement? There is no composite authentication strategy I could use.

```
jenkins-operator-76847b9976-bgqg4 jenkins-operator 2020-02-28T06:17:41.078Z	WARN	controller-jenkins	jenkins/jenkins_controller.go:152	Reconcile loop failed 10 times with the same error, giving up: couldn't poll data from Jenkins API, invalid status code returned: 403	{"cr": "jenkins"}
```

For anyone interested here is how it is being done

```
apiVersion: v1
kind: ConfigMap
metadata:
  name: jenkins-script-configuration
data:
  2-configure-github-oauth.groovy: |
    import hudson.security.SecurityRealm
    import org.jenkinsci.plugins.GithubSecurityRealm
    String githubWebUri = 'https://<COMPANY_GITHUB>'
    String githubApiUri = 'https://<COMPANY_GITHUB>/api/v3'
    String clientID = 'xxx'
    String clientSecret = 'xxx'
    String oauthScopes = 'read:org'
    SecurityRealm github_realm = new GithubSecurityRealm(githubWebUri, githubApiUri, clientID, clientSecret, oauthScopes)
    //check for equality, no need to modify the runtime if no settings changed
    if(!github_realm.equals(Jenkins.instance.getSecurityRealm())) {
        Jenkins.instance.setSecurityRealm(github_realm)
        Jenkins.instance.save()
    }
  
  3-configure-github-authorization-strategy.groovy: |
    import org.jenkinsci.plugins.GithubAuthorizationStrategy
    import hudson.security.AuthorizationStrategy

    //permissions are ordered similar to web UI
    //Admin User Names
    String adminUserNames = 'xxx'
    //Participant in Organization
    String organizationNames = ''
    //Use Github repository permissions
    boolean useRepositoryPermissions = true
    //Grant READ permissions to all Authenticated Users
    boolean authenticatedUserReadPermission = true
    //Grant CREATE Job permissions to all Authenticated Users
    boolean authenticatedUserCreateJobPermission = false
    //Grant READ permissions for /github-webhook
    boolean allowGithubWebHookPermission = true
    //Grant READ permissions for /cc.xml
    boolean allowCcTrayPermission = false
    //Grant READ permissions for Anonymous Users
    boolean allowAnonymousReadPermission = false
    //Grant ViewStatus permissions for Anonymous Users
    boolean allowAnonymousJobStatusPermission = false

    AuthorizationStrategy github_authorization = new GithubAuthorizationStrategy(adminUserNames,
        authenticatedUserReadPermission,
        useRepositoryPermissions,
        authenticatedUserCreateJobPermission,
        organizationNames,
        allowGithubWebHookPermission,
        allowCcTrayPermission,
        allowAnonymousReadPermission,
        allowAnonymousJobStatusPermission)
        
    //check for equality, no need to modify the runtime if no settings changed
    if(!github_authorization.equals(Jenkins.instance.getAuthorizationStrategy())) {
        Jenkins.instance.setAuthorizationStrategy(github_authorization)
        Jenkins.instance.save()
    }
```

Related issue (closed):
https://github.com/jenkinsci/kubernetes-operator/issues/11

**Comment by tomaszsek** [comment]
Fixed via PM

**Comment by wendtek** [comment]
What was the solution for this issue? We are facing the same thing and so far the solution is non-obvious to me.

**Comment by en7h** [comment]
I am also facing the same issue and would much appreciate a redacted solution be posted to the issue before closure 👍

**Comment by en7h** [comment]
@wendtek 

For what its worth I have solved this for my use case piecing together information from #11 

The user `jenkins-operator` needs to have access to administer the system, when you enable GitHub OAuth and set it as your security realm, `jenkins-operator` will still exist as a user.

Further, when you enable GitHub OAuth as your **authorization** strategy `jenkins-operator` will then require OAuth credentials to access Jenkins - I did not want to go through creating a service account `jenkins-operator` which may be impossible if using a public git host.

You **authentication** (security realm) differs from your **authorization** strategy.

I fixed this using `matrix-auth` but you could also fix this with another **authorization strategy** that still allows jenkins underlying authorization to come through.

**Add matrix-auth to your plugins**
Versions are current as of this post, update accordingly.

```yaml
plugins:
  - name: github-oauth
    version: "0.33"
  - name: matrix-auth
    version: "2.6.6"
```

**Add matrix-auth authorization to your CasC**
If you have configuration which sets authorization strategy for `github-oauth`, remove it.

Add a configuration entry, customize permissions as necessary.

Note: **`"Overall/Administer:jenkins-operator"`** jenkins-operator has administrator permissions.

```yaml
jenkins:
  authorizationStrategy:
    globalMatrix:
      permissions:
      - "Overall/Read:authenticated"
      - "Overall/Administer:jenkins-operator"
      - "Agent/Build:authenticated"
      - "Credentials/View:authenticated"
      - "Job/Build:authenticated"
      - "Job/Cancel:authenticated"
      - "Job/Discover:authenticated"
      - "Job/Read:authenticated"
      - "Job/Workspace:authenticated"
      - "Lockable Resources/Reserve:authenticated"
      - "Lockable Resources/Unlock:authenticated"
      - "Lockable Resources/View:authenticated"
      - "Run/Delete:authenticated"
      - "Run/Replay:authenticated"
      - "Run/Update:authenticated"
      - "SCM/Tag:authenticated"
      - "View/Configure:authenticated"
      - "View/Create:authenticated"
      - "View/Delete:authenticated"
      - "View/Read:authenticated"
```

**Roll your Jenkins instance**
I removed the `Jenkins` crd for my instance and added it back to completely re-roll.
